server:
  port: 16000

spring:
  application:
    name: 'consumer-server'
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        wait-duration-in-open-state: 5000 #熔断器从打开到半开的时间
#        failure-rate-threshold: 10 #熔断器打开的失败阈值
#        event-consumer-buffer-size: 5 #事件缓冲区大小
#        automatic-transition-from-open-to-half-open-enabled: true #是否自动从打开到半开
#        record-exceptions: java.lang.Exception #记录的异常
#        register-health-indicator: true #健康监测
#        minimum-number-of-calls: 5 #触发熔断机制的最小请求个数
#        permitted-number-of-calls-in-half-open-state: 3 #半开状态下允许通过的请求个数
#    instances:
#      backendA:
#        base-config: default
#      backendB:
#        base-config: default
#        wait-duration-in-open-state: 3000
#        failure-rate-threshold: 15

#resilience4j:
#  retry:
#    configs:
#      default:
#        max-attempts: 5
#        wait-duration: 1000
#        enable-exponential-backoff: true
#        retry-exceptions:
#          - java.lang.Exception
#
#    instances:
#      retry1:
#       base-config: default
#      retry2:
#        base-config: default
#        max-attempts: 5
#        wait-duration: 500

#resilience4j:
#  ratelimiter:
#    configs:
#      default:
#        limit-for-period: 5
#        limit-refresh-period: 2000
#        timeout-duration: 5
#    instances:
#      rate1:
#        base-config: default
#      rate2:
#        base-config: default
#        limit-for-period: 3

resilience4j:
  thread-pool-bulkhead:
    configs:
      default:
        max-thread-pool-size: 10
        queue-capacity: 1
        keep-alive-duration: 20ms
        core-thread-pool-size: 1
    instances:
      bulkhead1:
        base-config: default